import 'package:compareitr/core/common/entities/cart_entity.dart';

class CartModel extends CartEntity {
  CartModel({
    String? id, // Make id optional
    required String cartId,
    required String imageUrl,
    required String itemName,
    required String shopName,
    required double price,
    required int quantity,
    required String measure,
  }) : super(
          id: id ??
              '', // Use an empty string or a default value if id is not provided
          cartId: cartId,
          itemName: itemName,
          shopName: shopName,
          price: price,
          quantity: quantity,
          imageUrl: imageUrl,
          measure: measure,
        );

  factory CartModel.fromJson(Map<String, dynamic> json) {
    return CartModel(
      id: json['id'] as String?, // Adjust field names to match DB schema
      cartId: json['cartId'] as String,
      itemName: json['itemName'] as String,
      shopName: json['shopName'] as String,
      price: double.parse(json['price'].toString()), // Ensure `price` is double
      quantity: json['quantity'] as int,
      imageUrl: json['imageUrl'] as String,
      measure: json['measure'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'cartId': cartId,
      'itemName': itemName,
      'shopName': shopName,
      'price': price,
      'quantity': quantity,
      'imageUrl': imageUrl,
      'measure': measure,
      // Do not include 'id' here if it's generated by the database
    };
  }
}
