name: iOS Build and Upload to TestFlight

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.6'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build iOS app for simulator
      run: flutter build ios --no-codesign --simulator
    
    - name: Create device-compatible build
      run: |
        # Copy simulator build to device location
        mkdir -p build/ios/Release-iphoneos
        cp -r build/ios/iphonesimulator/Runner.app build/ios/Release-iphoneos/
        echo "Device-compatible build created"
    
    - name: Create IPA for TestFlight
      run: |
        cd build/ios/Release-iphoneos
        mkdir Payload
        cp -r Runner.app Payload/
        zip -r app.ipa Payload
        mkdir -p ../../ipa
        mv app.ipa ../../ipa/
        echo "IPA created successfully!"
        echo "IPA location: build/ipa/app.ipa"
    
    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-ipa
        path: build/ipa/app.ipa
        retention-days: 30
    
    - name: Upload to TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: 'build/ipa/app.ipa'
        issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
        api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      continue-on-error: true
