name: iOS Build and Upload to TestFlight

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.6'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Import Code Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.CERTIFICATE_P12_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}
    
    - name: Download Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.example.compareitr'
        issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
        api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
    
    - name: Set up keychain for Flutter
      run: |
        # Set the keychain as default
        security default-keychain -s signing_temp.keychain
        security unlock-keychain -p "" signing_temp.keychain
        
        # List certificates to verify
        security find-identity -v -p codesigning
        
        # Set keychain settings
        security set-key-partition-list -S apple-tool:,apple: -k "" signing_temp.keychain
        
        # Set environment variables for Flutter
        echo "FLUTTER_BUILD_MODE=release" >> $GITHUB_ENV
        echo "CODE_SIGN_IDENTITY=Apple Distribution: Samuele Puteho (3MUKMZ9YDV)" >> $GITHUB_ENV
        echo "PROVISIONING_PROFILE_SPECIFIER=CompareItr Distribution" >> $GITHUB_ENV
    
    - name: Build iOS app for device
      run: flutter build ipa --release --export-method=app-store
    
    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-ipa
        path: build/ios/ipa/*.ipa
        retention-days: 30
    
    - name: Upload to TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: 'build/ios/ipa/*.ipa'
        issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
        api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      continue-on-error: true
