name: iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.6'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build iOS app for simulator
      run: flutter build ios --release --no-codesign --destination 'platform=iOS Simulator,name=iPhone 16'
    
    - name: Create build archive
      run: |
        cd build/ios/Release-iphonesimulator
        mkdir -p ../../archive
        zip -r ../../archive/ios-build.zip Runner.app
        echo "iOS build completed successfully!"
        echo "Build location: build/archive/ios-build.zip"
