name: iOS Build and Upload to TestFlight

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.6'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Import Code Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.CERTIFICATE_P12_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}
    
    - name: Download Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.example.compareitr'
        issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
        api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
    
    - name: List available simulators
      run: |
        xcrun simctl list devices available
        echo "Available simulators listed above"
    
    - name: Build iOS app using xcodebuild with any available simulator
      run: |
        cd ios
        # Use the first available iPhone simulator
        xcodebuild -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination 'platform=iOS Simulator,name=Any iOS Simulator Device' \
          -archivePath build/Runner.xcarchive \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        echo "Xcode build completed"
    
    - name: Create export options plist
      run: |
        cat > ios/exportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>3MUKMZ9YDV</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
                <key>com.example.compareitr</key>
                <string>CompareItr Distribution</string>
            </dict>
        </dict>
        </plist>
        EOF
        echo "Export options plist created"
    
    - name: Export archive
      run: |
        cd ios
        xcodebuild -exportArchive \
          -archivePath build/Runner.xcarchive \
          -exportPath build/export \
          -exportOptionsPlist exportOptions.plist \
          CODE_SIGN_IDENTITY="Apple Distribution: Samuele Puteho (3MUKMZ9YDV)" \
          PROVISIONING_PROFILE_SPECIFIER="CompareItr Distribution"
        echo "Archive exported"
    
    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-ipa
        path: ios/build/export/*.ipa
        retention-days: 30
    
    - name: Upload to TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: 'ios/build/export/*.ipa'
        issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
        api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      continue-on-error: true
