name: iOS Build and Upload to TestFlight

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.6'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Import Code Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.CERTIFICATE_P12_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}
    
    - name: Download Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.example.compareitr'
        issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
        api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
    
    - name: Build iOS app using xcodebuild
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath build/Runner.xcarchive \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        echo "Xcode build completed"
    
    - name: Extract archive
      run: |
        cd ios
        xcodebuild -exportArchive \
          -archivePath build/Runner.xcarchive \
          -exportPath build/export \
          -exportOptionsPlist exportOptions.plist \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        echo "Archive extracted"
    
    - name: Create export options plist
      run: |
        cat > ios/exportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>3MUKMZ9YDV</string>
        </dict>
        </plist>
        EOF
        echo "Export options plist created"
    
    - name: Embed provisioning profile
      run: |
        # Copy the provisioning profile into the app bundle
        cp "/Users/runner/Library/MobileDevice/Provisioning Profiles/d62b673d-a933-4d3c-bb01-406fe11f2b94.mobileprovision" "ios/build/export/Runner.app/embedded.mobileprovision"
        echo "Provisioning profile embedded"
    
    - name: Code sign all frameworks
      run: |
        # Set the keychain as default
        security default-keychain -s signing_temp.keychain
        security unlock-keychain -p "" signing_temp.keychain
        
        # Sign all frameworks
        find ios/build/export/Runner.app/Frameworks -name "*.framework" -exec codesign --force --sign "Apple Distribution: Samuele Puteho (3MUKMZ9YDV)" {} \;
        echo "All frameworks code signed"
    
    - name: Code sign the app
      run: |
        # Code sign the main app
        codesign --force --sign "Apple Distribution: Samuele Puteho (3MUKMZ9YDV)" ios/build/export/Runner.app
        echo "App code signed"
    
    - name: Create IPA for TestFlight
      run: |
        cd ios/build/export
        mkdir Payload
        cp -r Runner.app Payload/
        zip -r app.ipa Payload
        mkdir -p ../../ipa
        mv app.ipa ../../ipa/
        echo "IPA created successfully!"
        echo "IPA location: ios/ipa/app.ipa"
    
    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-ipa
        path: ios/ipa/app.ipa
        retention-days: 30
    
    - name: Upload to TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: 'ios/ipa/app.ipa'
        issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
        api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      continue-on-error: true
